---
- name: install packages
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: install vim and git
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - zip
        - wget
        